default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yelp_development
  username: robertclayton
  password: 31ronald


test:
  <<: *default
  database: yelp_test
  username: robertclayton
  password: 31ronald


production:
  <<: *default
  database: yelp_production
  username: robertclayton
  password: 31ronald
